### PR TITLE
Support Embulk 0.11

### PR DESCRIPTION
**Pull request by joker1007**
# What

- Update dependent libraries to support embulk-0.11
- Fix embulk SPI usage
- Use [json-path](https://github.com/json-path/JsonPath) instead of JsonPathCompiler

# Breaking Changes
To simplify the handling of json-path, a new `json_path` parameter was added instead of writing json-path in `name`.
You need to rewrite config if you used to write json-path directly in name.

# Future Work
- Refactoring has not finished
- Setup CI
- Performance optimization

### CODE REVIEW

**Comment by sonots** [comment]
@joker1007 Could you describe elaborately about the critical reason why we need breaking changes?

**Comment by sonots** [comment]
@joker1007 Let me make sure if my understanding is correct.

Q1. Is below change correct?

Configuration before this change:

```yaml
columns:
  - {name: "$.json1.field1", type: string}
  - {name: "$.json1.field2", type: string}
```

Configuration after this change:

```yaml
columns:
  - {name: "json1", json_path: "$.json1.field1", type: string}
  - {name: "json1", json_path: "$.json1.field2", type: string}
```

Q2. If Q1 is correct, my another question is, is it still possible to specify the same `name` ("json1") twice in one config?

**Comment by joker1007** [comment]
@sonots 

Thank you for your comments.

# Reason of the breaking change
- JsonPathCompiler is based on the old json-path. It is hard work to continue to catch up json-path updates
- We need a new maven repository for JsonPathCompiler if we continue to use it
- some json-path APIs to handle path tokens is private class. We cannot touch them.
- complex JSONPath can be easily supported if we don't derive column names from JSONPath.

# Answer to questions
Q1: That's right. 
Q2: It's impossible now. I have two options.
1. add `rename_to` option to set column name explicitly
2. copy field with filter-column plugin and use this.

Personally, I prefer to choose 1.

**Comment by joker1007** [comment]
By the way, there is a function to get data by JSONPath in embulk-filter-column as well, but I think it would be better to separate out the function to another plugin, or consolidate it into typecast.

**Comment by sonots** [comment]
@joker1007 

> Reason of the breaking change

Okay, let me describe the critical reason here for me.
* `medjed.JsonPathCompiler` has a method `getRoot` which supports to obtain the root name of a json path such as `$.json1.field1` -> `json1`.
  * It enabled us to obtain a column name from an embulk config such as `{name: "$.json1.field1"}` ->  `json1`.
*  On the other hand, `json-path` does not provide a similar method of `getRoot` (Actually, it hides such function as a private method, and this is reason why `medjed.JsonPathCompiler` forked `json-path` library).
    * So, we cannot obtain a column name from json-path now,  thus it is required to write both column name and json path like `{name: "json1", json_path: "$.json1.field1"}` within a config.

> add `rename_to` option to set column name explicitly
> copy field with filter-column plugin and use this.

I do not get how it will work 🤔 

```
columns:
  - {name: "$.json1.field1", type: string}
  - {name: "$.json1.field2", type: string}
```

converts `field1` and `filed2` json fields of `json1` column into `string` type as

```
{"json1":{"field1":1,"field2":2}}
```
to
```
{"json1":{"field1":"1","field2":"2"}}
```

It does not rename or copy anything.

**Comment by joker1007** [comment]
Well, I understand and I was fundamentally mistaken! 
The JSONPath that is set at `name` means the location of typecast target. It doesn't mean extracting value.

So, I enable to write below format.

```yaml
columns:
  - {name: "json1", json_path: "$.json1.field1", type: string}
  - {name: "json1", json_path: "$.json1.field2", type: string}
 ```

Is it all right?

**Comment by sonots** [comment]
@joker1007 

```
columns:
  - {name: "json1", json_path: "$.json1.field1", type: string}
  - {name: "json1", json_path: "$.json1.field2", type: string}
 ```

Yes, no problem if this is possible.

**Comment by sonots** [comment]
By the way, below spec is another option. Demerit is bigger backward incompatibility, though.

```
columns:
  - {name: "json1", json_path: "$.field1", type: string}
  - {name: "json1", json_path: "$.field2", type: string}
 ```

**Comment by joker1007** [comment]
After much thought, I succeeded in making it 0.11 compliant while maintaining the original format.
As a side effect, this plugin can support slice array format and predication format now.

But, only the JSONPath assertion could not be implemented because it depends on an API that I just can't touch.

**Comment by sonots** [comment]
@joker1007 
Cool, merge this whenever you want. 👍

**Pull request merged**
